AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/helpers/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

