version: '3'
services:
  db:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file:
      - '.env'
  web:
    build: .
    depends_on:
      - 'db'
    ports:
      - '80:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"

volumes:
  db:
