version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose up -d

      - run:
          name: Run tests
          command: docker-compose exec web bundle exec rspec