version: 2.1
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose up -d

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup DB
          command: docker-compose exec web rails db:create db:migrate

      - run:
          name: Run tests
          command: docker-compose exec web bundle exec rspec

      - store_artifacts:
          path: coverage