version: 2.1
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose up -d

      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5434 -timeout 1m

      - run:
          name: Setup DB
          command: docker-compose exec web rails db:create db:migrate

      - run:
          name: Run tests
          command: docker-compose exec web bundle exec rspec

      - store_artifacts:
          path: coverage