default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 2137

development:
  <<: *default
  database: link_shortener_dev

test:
  <<: *default
  database: link_shortener_test

production:
  <<: *default
  database: link_shortener_prod
